replicaCount: 1

image:
  repository: baseline-api
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

config:
  LOG_LEVEL: "info"
  SERVICE_NAME: "baseline-api"
  DB_HOST: "postgres-sde-benchmark-postgresql.sde-benchmark.svc.cluster.local"
  DB_PORT: "5432"
  DB_USER: "testuser"
  DB_NAME: "testdb"

postgres:
  secretName: "postgres-sde-benchmark-postgresql"
  passwordKey: "password"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi