apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-consumer
  labels:
    app: event-consumer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: event-consumer
  template:
    metadata:
      labels:
        app: event-consumer
    spec:
      containers:
        - name: event-consumer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}

          envFrom:
            - configMapRef:
                name: event-consumer-config

          resources:
            {{- toYaml .Values.resources | nindent 12 }}