apiVersion: v1
kind: Service
metadata:
  name: event-consumer
spec:
  type: {{ .Values.service.type }}
  selector:
    app: event-consumer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http