apiVersion: apps/v1
kind: Deployment
metadata:
  name: baseline-api
  labels:
    app: baseline-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: baseline-api
  template:
    metadata:
      labels:
        app: baseline-api
    spec:
      containers:
        - name: baseline-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}

          envFrom:
            - configMapRef:
                name: baseline-api-config

          resources:
            {{- toYaml .Values.resources | nindent 12 }}