apiVersion: v1
kind: Service
metadata:
  name: baseline-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: baseline-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http