apiVersion: v1
kind: Service
metadata:
  name: optimized-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: optimized-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http