replicaCount: 1

image:
  repository: event-consumer
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9000

config:
  APP_MODE: "prod"
  LOG_LEVEL: "info"
  SERVICE_NAME: "event-consumer"

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 300m
    memory: 400Mi